[package]
name = "gui-patcher"
version = "0.1.1"
edition = "2021"
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "^0.28"
egui_extras = { version = "^0.28", features = ["image"] }
eframe = { version = "^0.28", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
rfd = {version = "^0.14", default-features = false, features = ["xdg-portal", "async-std"]}
log = "^0.4"
flume = "^0.11"
eyre = "^0.6"
lazy_static = "^1.4"

# You only need serde if you want app persistence:
serde = { version = "^1.0", features = ["derive"] }

# native dependecies:
geckolib = { path = "../../geckolib", features = ["progress"] }
env_logger = "^0.11"
futures-lite = "^2.3"
async-std = "^1.12"
image = { version = "^0.25", features = ["png"]}
regex = "^1.10"
pin-project = "^1.1"

[features]
default = ["parallel"]
parallel = ["geckolib/parallel"]
