[package]
name = "geckolib"
version = "0.1.2"
edition = "2024"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "geckolib"
path = "src/lib.rs"

[dependencies]
log = "^0.4"
aes = "^0.8"
sha1_smol = "^1.0"
cbc = { version = "^0.1" }
eyre = "^0.6"
thiserror = "^2.0"
num = "^0.4"
toml = "^0.9"
semver = { version = "^1.0", features = ["serde"]}
zip = { version = "^6.0", default-features = false, features = ["deflate"] }
regex = "^1.10"
rustc-demangle = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"
byteorder = "^1.4"
futures = "^0.3"
image = { version = "^0.25", default-features = false, features = [
    "jpeg",
    "png",
] }
goblin = "^0.10"
lazy_static = "^1.5"
pin-project = "^1.1"
rayon = { version = "^1.10", optional = true }
human_bytes = { version = "^0.4", optional = true, default-features = false }
static_assertions = "^1.1"
syn = "^2.0"
encoding_rs = "^0.8"
indextree = { version = "^4.7" }
bsdiff = { version = "^0.2" }
deko = { version = "^0.5", default-features=false, features = ["bzip2"] }
itertools = "^0.14"
relative-path = { version = "^2.0", features = ["serde"] }
sha3 = "^0.10"
setsum = "^0.7"
hex = "^0.4"

[dependencies.bzip2]
version = "^0.5"
features = ["libbz2-rs-sys"]

[features]
default = ["parallel", "progress"]
web = []
parallel = ["rayon", "image/rayon"]
log = []
progress = ["human_bytes"]
